var target = document.getElementById('question');
var questions = [
    'In your opinion, what is a product design?',
    'Tell us about the newest thing you’ve learned that has improved your design work. What was it?',
    'In your opinion, how should a good design process start? Why?',
    'What’s the most important aspect of your job?',
    'What is your favorite piece in your portfolio?',
    'How would you redesign iphone’s messaging interface?',
    'Tell me about your design challenge',
    'What could Siri do better?',
    'What is the most challenging project you have ever worked on?',
    'What do you want to work at here?',
    'Describe the project that you had the most trouble with. What would you have done differently?​',
    'What was the biggest takeaway from your current job that you will carry with you throughout your career?​',
    'How do you keep your team engaged?',
    'Give an example of how you set goals and achieve them​.',
    'Tell me about a time when you solved a conflict at work.​',
    'Why do you want to change jobs? Why now?',
    'Share an example of how you were able to motivate employees or co-workers.',
    'What do you do when the requirement from the stakeholder is vague?',
    'How do you stay organized?',
    'Give an example of an occasion when you used logic to solve a problem.',
    'What do you do if you don not know the solution for a certain problem and nobody can help at the moment?',
    'How do you experiment?',
    'What websites do you spend a lot of time on?',
    'What do you do if you disagree with your boss?',
    'Talk about a time that you failed.​',
    'What was the design process of your project?',
    'Tell me about a time that you did something wrong, and what you learned from the process',
    'Where do you find inspiration?',
    'Tell me about the projects you’re most proud of and why. What was your role?',
    'How do you deal with feedback?',
    'How do you hand off a project?',
    'Why did you become a designer?',
    'How would you describe your design research?',
    'Please explain the three best projects from your portfolio',
    'What would you say will be future of design? Or the next big thing?',
    'What is your biggest design challenge?',
    'What are your strengths?',
    'How do you learn and grow your knowledge and expertise?',
    'What constitutes good design?',
    'What do you do in your current job?',
    'How many people are in your team?',
    'Do you follow any designers?',
    'How do you keep yourself updated with the latest design trends?',
    'Which company do you think does the best branding?',
    'What’s your favorite product or app and why?',
    'Which product’s design do you dislike and how would you change it?',
    'Can you code?',
    'Have you faced any problems while working with developers? How do you solve it?',
    'What do you do when project managers or clients don’t like your design?',
    'Do you have experience leading a team or conducting presentations?',
    'How do you handle critique on your designs?',
    'Have you done usability testing?',
    'Talk me through your design process.',
    'When do you know a design is complete?',
    'How do you stay organized or keep up with deadlines?',
    'What’s the role of a product designer? What does design mean to you?',
    'What do you enjoy most about working in design?',
    'Have you revisited your key success metrics since successful launches? How are they the same or different?',
    'How do you handle several people who ask you something who all have priorities?',
    'Reimagine and redesign an existing digital product of your choice that showcases your skills and abilities to solve a complex problem as a designer.',
    'Tell me about a product that you really love and why. How could it be improved?',
    'How could you describe interaction design to someone don not know interaction design?',
    'Tell me the high-level thinking behind your application.',
    'Do you use data for design decisions?',
    'If you could improve one mobile experience, what would it be and why?',
    'Show us an example of a website with great design.',
    'What type of technology are you interested in?',
    'Explain how you work with engineers, designers, and product managers.',
    'Looking back at the design for this project, what would you change visually?',
    'Recommend to us a design related book, then explain why you have recommended it.',
    'What designer has had the biggest influence on your work? Why?',
    'What advice would you give to a young designer that just finished studying?',
    'How do you rate your skills in product thinking, interaction design, and visual design?',
    'What led you to your final design? Describe the tradeoffs you considered.',
    'How do you validate your decisions?',
    'What type of process do you use in conducting user research?',
    'Tell me about your experience with A/B testing. How long do you have experience with mobile and web responsive projects?',
    'Talk about a time you negotiated your way to the ideal UX solution?',
    'What would you do if you know you are going to miss a deadline?',
    'How do you handle a situation when a developer doesn’t create the product the way you designed it?',
    'How do you know your designs meet the customers’ demands?',
    'What are you passionate about?',
    'Can you describe a time when your recommendation improved the design process?',
    'Describe a time when someone disagreed with you. How was this resolved?',
    'As a designer, what motivates you and what demotivates you?',
    'What is product thinking?',
    'Which company do you think have the best design?',
    'What is the typical day like for someone in this position?',
    'What are the learning/mentoring opportunities within the company?',
    'Have can you collaborate effectively with the remote team?',
    'Talk through a recent project thoroughly and tell me what you learnt',
    'What metrics signaled you to work on problem?',
    'Redesign a TV remote',
    'Critique an app on your phone',
    'Critiquing YouTube video app',
    'Rethink the ATM',
    'Do you lean on data or intuition for design decisions? What do you do when you don’t have data?',
    'As a CEO, why should I invest in design?',
    'How do you validate or test the usability of a design?',
    'What tools do you use?',
    'Why are you interested in this company?',
    'Explain Product Design in 10 words',
    'How do you define the role of the Product Designer? Which parts of the product and process do you see as your responsibility and which are not?',
    'Do you consider yourself technically inclined? What is the most technically-challenging project you have tackled?',
    'If you had to pick one of the following as your greatest strength, what would it be',
    'What inspires your thinking about design?',
    'Tell me about your current customers or clients',
    'Tell me about a time you were surprised by user reactions during user research',
    'Are you more comfortable designing on a team or solo?',
    'Tell me a little about your current team`s structure.',
    'Do you have experience working in an agile development environment?',
    'What is the best way for design to integrate into the agile process?',
    'What is different about managing designers? Can you talk a little bit about the pitfalls of managing designers? How do you motivate designers?'
];

var lastUsed = "";

function randomQuestion () {
    document.getElementById("button").innerHTML = "Next Question";
    var i = (Math.random() * questions.length) | 0;
    if (i != lastUsed) {
        var random = questions[i];
        question.innerText = random;
        lastUsed = i;
    } else {
        newTitle ()
    }
}